#!/usr/bin/env perl

binmode STDOUT, ":utf8";

use FindBin;
use lib "$FindBin::Bin/../lib";

use Act::Config;
use Act::Schema;

my $ActSchema = Act::Schema->connect(
  $Config->database_dsn,
  $Config->database_user,
  $Config->database_passwd,
  undef
);


my $community_events_set = $ActSchema
  ->resultset('CommunityEvent')
  ->search( undef, { order_by => 'edition' });

# use DDP; p $talks_set;

my $community_event;
my $community_event__abstract = '<< undef >>';

# format STDOUT_TOP =
# _______________________________________________________________________
# .

format STDOUT =
c_evnt_id : @>>>>>>>>>> title     : @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<...
            $community_event->community_event_id, $community_event__abstract
conf_id   : @>>>>>>>>>> syndicate : @<<<<<<<<<< edition   : @<<<<<<<<<<
            $community_event->conf_id, $community_event->syndicate, $community_event->edition


.

while ( $community_event = $community_events_set->next ) {
# $community_event__abstract = $community_event->abstract;
  write ();
};


