#!/usr/bin/env perl

binmode STDOUT, ":utf8";

use FindBin;
use lib "$FindBin::Bin/../lib";

use Act::Config;
use Act::Schema;

my $ActSchema = Act::Schema->connect(
  $Config->database_dsn,
  $Config->database_user,
  $Config->database_passwd,
  undef
);

my $users_set = $ActSchema
  ->resultset('User');
# ->all;
# ->search_rs( {
#   conf_id => "nlpw%"
# }
  #);

use DDP; p $users_set;

print "users list:\n";
while ( my $user = $users_set->next ) {
p $user{_column_data};
# print $user->user_id, " ",$user->login, " ", $user->country, " ", $user->pause_id, "\n";
# print $user->abstract, "\n" x2;
};
print "users total: ", $users_set->count, "\n";


	

