#!/usr/bin/env perl

use strict;
use warnings;

binmode STDOUT, ":utf8";

use FindBin;
use lib "$FindBin::Bin/../lib";

use Act::Config;
use Act::Schema;

my $ActSchema = Act::Schema->connect(
  $Config->database_dsn,
  $Config->database_user,
  $Config->database_passwd,
  undef
);


my $conferences_set = $ActSchema
  ->resultset('Conference')
  ->search( undef, { order_by => 'edition' });

my $conference;
my $conference__title = '<< ?? >>';

format STDOUT_TOP =
conf_id     syndicate   edition     title                              
_______________________________________________________________________
.

format STDOUT =
@<<<<<<<<<< @<<<<<<<<<< @<<<<<<<<<< @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<...
$conference->conf_id, $conference->syndicate, $conference->edition, $conference__title
.


while ( $conference = $conferences_set->next ) {
# $conference__title = $conference->title;
  write ();
};


