#!/usr/bin/env perl

binmode STDOUT, ":utf8";

use FindBin;
use lib "$FindBin::Bin/../lib";

use Act::Config;
use Act::Schema;

my $ActSchema = Act::Schema->connect(
  $Config->database_dsn,
  $Config->database_user,
  $Config->database_passwd,
  undef
);

my $talks_set = $ActSchema
  ->resultset('Talk')
  ->search( undef, { order_by => 'talk_id' });

use DDP; p $talks_set;

my $talk;
my $talk__abstract;
my $talk__syndicate;
my $talk__edition;
my $talk__user;

# format STDOUT_TOP =
# _______________________________________________________________________
# .

format STDOUT =
Talk_id   : @>>>>>>>>>> Title     : @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<...
            $talk->talk_id,         $talk->title    
Conf_id   : @>>>>>>>>>> Syndicate : @<<<<<<<<<< Edition   : @<<<<<<<<<<
            $talk->conf_id,         $talk__syndicate,     $talk__edition
User_id   : @>>>>>>>>>> Full Name : @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<...
            $talk->user_id,         $talk__user
Language  : @<<<<<<<<<< Target    : @<          Accepted  : @<         
            $talk->lang,            $talk->datetime,        $talk->accepted
DateTime  : @<<<<<<<<<<<<<<<<<<<< : @>>>min.    Room      : @<<<<<<<<<<
$talk->datetime,                    $talk->duration         $talk->room
Abstract  : ^<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            $talk__abstract
            ^<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< ~~
            $talk__abstract

.

while ( $talk = $talks_set->next ) {
  $talk__abstract  = $talk->abstract;
  $talk__syndicate = $talk->conference
    ? $talk->conference->syndicate : '---';
  $talk__edition   = $talk->conference
    ? $talk->conference->edition : '---';
  $talk__user       = $talk->user ?
    $talk->user->full_name : '---';
  write ();
};


